### ISSUE TITLE
Provide a method to invalidate the cache

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#9] opened 2013-08-24 19:49 UTC
Implement functionality to invalidate the cache. This will be used when users log out of the application and switch accounts. 

Provide two methods of cache invalidation
- Targeted entities
- Entire collection

**Comment by jyore** [comment] 2013-08-24 19:54
Will put up one to remove a certain entry soon. To do the remove all, I need to go into the underlying APIs and provide a method to get a collection of keys to iterate over and remove.

**Comment by jyore** [comment] 2013-09-11 16:27
Since the framework changed and the caching changed, the invalidation will now happen differently. Because of this I am closing as it is a duplicate of another feature being worked on.

duplicates #11

**Closed as completed by jyore** 2013-09-11 16:27 UTC
Labels: duplicate, feature
